[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "colorama>=0.4.6",
    "pyfiglet>=1.0.4",
    "requests>=2.32.5",
    "rich>=14.2.0",
]
